// <auto-generated />
using System;
using A2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127190836_LogCotacao")]
    partial class LogCotacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("A2.Models.CategoriaDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasDespesa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Despesas com locomoção",
                            Nome = "Transporte"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Despesas com refeições",
                            Nome = "Alimentação"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Despesas com estadias",
                            Nome = "Hospedagem"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Material de Escritório",
                            Nome = "Material"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "Outras despesas gerais",
                            Nome = "Outros"
                        });
                });

            modelBuilder.Entity("A2.Models.ComprovanteDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DespesaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamanhoArquivo")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DespesaId");

                    b.ToTable("ComprovantesDespesa");
                });

            modelBuilder.Entity("A2.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CentroDeCusto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int?>("GestorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CentroDeCusto = "CC001",
                            Nome = "Recursos Humanos"
                        });
                });

            modelBuilder.Entity("A2.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("MoedaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestacaoContasId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxaCambio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorEmBrl")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("MoedaId");

                    b.HasIndex("PrestacaoContasId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("A2.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cnpj = "00.000.000/0001-00",
                            Nome = "FinOps Pro Ltda",
                            RazaoSocial = "FinOps Pro Ltda"
                        });
                });

            modelBuilder.Entity("A2.Models.Feriado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feriados");
                });

            modelBuilder.Entity("A2.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CnpjCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("A2.Models.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosPosteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("A2.Models.LogCotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("MoedaBaseId")
                        .HasColumnType("int");

                    b.Property<int>("MoedaCotadaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Taxa")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("MoedaBaseId");

                    b.HasIndex("MoedaCotadaId");

                    b.ToTable("LogsCotacao");
                });

            modelBuilder.Entity("A2.Models.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Simbolo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Moedas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "BRL",
                            Nome = "Real Brasileiro",
                            Simbolo = "R$"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "USD",
                            Nome = "Dólar Americano",
                            Simbolo = "$"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "EUR",
                            Nome = "Euro",
                            Simbolo = "€"
                        });
                });

            modelBuilder.Entity("A2.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeneficiarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamentoEfetivada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPagamentoPrevista")
                        .HasColumnType("datetime2");

                    b.Property<int>("MoedaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrestacaoContasId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessadoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("SolicitacaoAdiantamentoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.HasIndex("MoedaId");

                    b.HasIndex("PrestacaoContasId");

                    b.HasIndex("ProcessadoPorId");

                    b.HasIndex("SolicitacaoAdiantamentoId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("A2.Models.PrestacaoContas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SaldoDevolucao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoReembolso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SolicitacaoAdiantamentoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDespesas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("SolicitacaoAdiantamentoId");

                    b.ToTable("PrestacoesContas");
                });

            modelBuilder.Entity("A2.Models.SolicitacaoAdiantamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataPagamentoAjustada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPagamentoRequerida")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MoedaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("MoedaId");

                    b.ToTable("SolicitacoesAdiantamento");
                });

            modelBuilder.Entity("A2.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Cpf = "00000000000",
                            CriadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 1,
                            Email = "admin@finops.com",
                            NomeCompleto = "Admin FinOps (RH)",
                            Perfil = 2
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Cpf = "11111111111",
                            CriadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 1,
                            Email = "lucas@finops.com",
                            NomeCompleto = "Lucas Henderson",
                            Perfil = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Cpf = "22222222222",
                            CriadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartamentoId = 1,
                            Email = "ana@finops.com",
                            NomeCompleto = "Ana Costa",
                            Perfil = 1
                        });
                });

            modelBuilder.Entity("A2.Models.ComprovanteDespesa", b =>
                {
                    b.HasOne("A2.Models.Despesa", "Despesa")
                        .WithMany("Comprovantes")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despesa");
                });

            modelBuilder.Entity("A2.Models.Departamento", b =>
                {
                    b.HasOne("A2.Models.Empresa", null)
                        .WithMany("Departamentos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("A2.Models.Despesa", b =>
                {
                    b.HasOne("A2.Models.CategoriaDespesa", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A2.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("A2.Models.Moeda", "Moeda")
                        .WithMany()
                        .HasForeignKey("MoedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A2.Models.PrestacaoContas", "PrestacaoContas")
                        .WithMany("Despesas")
                        .HasForeignKey("PrestacaoContasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Fornecedor");

                    b.Navigation("Moeda");

                    b.Navigation("PrestacaoContas");
                });

            modelBuilder.Entity("A2.Models.LogAuditoria", b =>
                {
                    b.HasOne("A2.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("A2.Models.LogCotacao", b =>
                {
                    b.HasOne("A2.Models.Moeda", "MoedaBase")
                        .WithMany()
                        .HasForeignKey("MoedaBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A2.Models.Moeda", "MoedaCotada")
                        .WithMany()
                        .HasForeignKey("MoedaCotadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MoedaBase");

                    b.Navigation("MoedaCotada");
                });

            modelBuilder.Entity("A2.Models.Pagamento", b =>
                {
                    b.HasOne("A2.Models.Usuario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A2.Models.Moeda", "Moeda")
                        .WithMany()
                        .HasForeignKey("MoedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A2.Models.PrestacaoContas", "PrestacaoContas")
                        .WithMany()
                        .HasForeignKey("PrestacaoContasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("A2.Models.Usuario", "ProcessadoPor")
                        .WithMany()
                        .HasForeignKey("ProcessadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("A2.Models.SolicitacaoAdiantamento", "SolicitacaoAdiantamento")
                        .WithMany()
                        .HasForeignKey("SolicitacaoAdiantamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Beneficiario");

                    b.Navigation("Moeda");

                    b.Navigation("PrestacaoContas");

                    b.Navigation("ProcessadoPor");

                    b.Navigation("SolicitacaoAdiantamento");
                });

            modelBuilder.Entity("A2.Models.PrestacaoContas", b =>
                {
                    b.HasOne("A2.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A2.Models.SolicitacaoAdiantamento", "SolicitacaoAdiantamento")
                        .WithMany()
                        .HasForeignKey("SolicitacaoAdiantamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("SolicitacaoAdiantamento");
                });

            modelBuilder.Entity("A2.Models.SolicitacaoAdiantamento", b =>
                {
                    b.HasOne("A2.Models.Usuario", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A2.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A2.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A2.Models.Moeda", "Moeda")
                        .WithMany()
                        .HasForeignKey("MoedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("CriadoPor");

                    b.Navigation("Departamento");

                    b.Navigation("Moeda");
                });

            modelBuilder.Entity("A2.Models.Usuario", b =>
                {
                    b.HasOne("A2.Models.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("A2.Models.Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("A2.Models.Despesa", b =>
                {
                    b.Navigation("Comprovantes");
                });

            modelBuilder.Entity("A2.Models.Empresa", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("A2.Models.PrestacaoContas", b =>
                {
                    b.Navigation("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
